import Navbar from '@/components/Navbar'
import Networkbar from '@/components/Networkbar'
import Tabs from '@/components/Tabs'
import '@/styles/globals.css'
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  return (
  <>
  <Head>
      <title>PrawnHub</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo.webp" />
  </Head>
  <Networkbar />
  <Navbar />
  <hr className='bg-black h-1 border-0'/>
  <Tabs />
  <Component {...pageProps} />
  </>
  )
}
